services:

  postgres:
    image: postgres:18-alpine
    container_name: superset-postgres

    restart: unless-stopped

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./volumes/postgres:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: superset-redis

    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  superset:
    build:
      context: .

    image: superset-custom:6.0.0

    container_name: superset

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    env_file:
      - .env

    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py

    ports:
      - "8088:8088"

    volumes:
      - ./volumes/superset_home:/app/superset_home

    command:
      - /app/docker/entrypoints/run-server.sh


volumes:
  redis-data:
